/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens;

/**
 *
 * @author 0069837
 */
public class TelaListagemQuartos extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaListagemFornecedores
     */
    public TelaListagemQuartos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPListagemQuartos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTQuartos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTBuscarNumeroQuartos = new javax.swing.JTextField();
        btnBuscarQuartos = new javax.swing.JButton();
        btnEliminarQuartos = new javax.swing.JButton();
        btnSairQuartos = new javax.swing.JButton();

        jPListagemQuartos.setBorder(javax.swing.BorderFactory.createTitledBorder("LISTAGEM - QUARTOS"));

        jTQuartos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número", "Andar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTQuartos);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel1.setText("Buscar");

        btnBuscarQuartos.setText("Buscar");

        btnEliminarQuartos.setText("Eliminar");

        btnSairQuartos.setText("Sair");

        javax.swing.GroupLayout jPListagemQuartosLayout = new javax.swing.GroupLayout(jPListagemQuartos);
        jPListagemQuartos.setLayout(jPListagemQuartosLayout);
        jPListagemQuartosLayout.setHorizontalGroup(
            jPListagemQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPListagemQuartosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTBuscarNumeroQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(btnBuscarQuartos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarQuartos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSairQuartos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPListagemQuartosLayout.setVerticalGroup(
            jPListagemQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPListagemQuartosLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPListagemQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTBuscarNumeroQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarQuartos)
                    .addComponent(btnEliminarQuartos)
                    .addComponent(btnSairQuartos))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPListagemQuartos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPListagemQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarQuartos;
    private javax.swing.JButton btnEliminarQuartos;
    private javax.swing.JButton btnSairQuartos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPListagemQuartos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTBuscarNumeroQuartos;
    private javax.swing.JTable jTQuartos;
    // End of variables declaration//GEN-END:variables
}
