/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens;

/**
 *
 * @author André Luiz Lopes
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        
   setExtendedState(MAXIMIZED_BOTH); //ABRIR TELA DE ABA A ABA
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnNome = new javax.swing.JLabel();
        btnCargo = new javax.swing.JLabel();
        btnAcesso = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        btnSair = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jCalendar2 = new com.toedter.calendar.JCalendar();
        telaFundo = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastros = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        menuCadastroHospede = new javax.swing.JMenuItem();
        menuConsultaHospede = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        btnCadastrarFuncionarios = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        menuReservas = new javax.swing.JMenu();
        btnCadastrarReserva = new javax.swing.JMenuItem();
        btnConsultarReserva = new javax.swing.JMenuItem();
        btnFinalizarReserva = new javax.swing.JMenuItem();
        menuRelatorio = new javax.swing.JMenu();
        jMenu17 = new javax.swing.JMenu();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenu18 = new javax.swing.JMenu();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenu19 = new javax.swing.JMenu();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenuItem35 = new javax.swing.JMenuItem();
        btnRelatorioHospedes = new javax.swing.JMenuItem();
        btnRelatorioFuncionarios = new javax.swing.JMenuItem();
        btnRelatorioFornecedores = new javax.swing.JMenuItem();
        menuSeguranca = new javax.swing.JMenu();
        tbnFazerBackup = new javax.swing.JMenuItem();
        btnRestaurarBackup = new javax.swing.JMenuItem();
        menuServicos = new javax.swing.JMenu();
        btnCadastrarServicos = new javax.swing.JMenuItem();
        btnConsultarServicos = new javax.swing.JMenuItem();
        menuFinanceiro = new javax.swing.JMenu();
        jMenu15 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu16 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        btnBalanco = new javax.swing.JMenuItem();
        menuVendas = new javax.swing.JMenu();
        btnProdutos = new javax.swing.JMenuItem();
        btnServicos = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Sistema Hotel - Desenvolvido por André Luiz Lopes");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(301, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(465, 465, 465))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hotel_building_stars_holiday_vacation_icon_196768 (1).png"))); // NOI18N
        jLabel3.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("HOTEL LOPES");

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setText("Nome");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel5.setText("Cargo");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setText("G.Acesso");

        btnNome.setText("nome");

        btnCargo.setText("texto");

        btnAcesso.setText("texto");

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel10.setText("CHECK-IN HOSPEDES");

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel11.setText("CHECK-OUT HOSPEDES");

        jCalendar1.setWeekOfYearVisible(false);

        jCalendar2.setWeekOfYearVisible(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator4)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnNome))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCargo))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnAcesso))
                                    .addComponent(btnSair))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCalendar2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel11))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel10)))
                .addGap(0, 173, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btnCargo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(btnAcesso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSair)
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCalendar2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel3);

        javax.swing.GroupLayout telaFundoLayout = new javax.swing.GroupLayout(telaFundo);
        telaFundo.setLayout(telaFundoLayout);
        telaFundoLayout.setHorizontalGroup(
            telaFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        telaFundoLayout.setVerticalGroup(
            telaFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        menuCadastros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/47-_iCal_256x256_35384.png"))); // NOI18N
        menuCadastros.setText("Cadastros ");

        jMenu8.setText("Hospedes");

        menuCadastroHospede.setText("Cadastramentos");
        menuCadastroHospede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroHospedeActionPerformed(evt);
            }
        });
        jMenu8.add(menuCadastroHospede);

        menuConsultaHospede.setText("Consultas");
        jMenu8.add(menuConsultaHospede);

        menuCadastros.add(jMenu8);

        jMenu9.setText("Quartos");

        jMenuItem4.setText("Cadastramentos");
        jMenu9.add(jMenuItem4);

        jMenuItem5.setText("Consultas");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem5);

        menuCadastros.add(jMenu9);

        jMenu10.setText("Funcionários");

        btnCadastrarFuncionarios.setText("Cadastramentos");
        btnCadastrarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarFuncionariosActionPerformed(evt);
            }
        });
        jMenu10.add(btnCadastrarFuncionarios);

        jMenuItem21.setText("Consultas");
        jMenu10.add(jMenuItem21);

        menuCadastros.add(jMenu10);

        jMenu11.setText("Fornecedores");

        jMenuItem22.setText("Cadastramentos");
        jMenu11.add(jMenuItem22);

        jMenuItem23.setText("Consultas");
        jMenu11.add(jMenuItem23);

        menuCadastros.add(jMenu11);

        jMenu12.setText("Produtos");

        jMenuItem24.setText("Cadastramentos");
        jMenu12.add(jMenuItem24);

        jMenuItem25.setText("Consultas");
        jMenu12.add(jMenuItem25);

        menuCadastros.add(jMenu12);

        jMenu13.setText("Serviços");

        jMenuItem26.setText("Cadastramentos");
        jMenu13.add(jMenuItem26);

        jMenuItem27.setText("Consultas");
        jMenu13.add(jMenuItem27);

        menuCadastros.add(jMenu13);

        jMenuBar1.add(menuCadastros);

        menuReservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1490820812-14_82398.png"))); // NOI18N
        menuReservas.setText("Reservas");

        btnCadastrarReserva.setText("Cadastrar ");
        btnCadastrarReserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastrarReservaMouseClicked(evt);
            }
        });
        menuReservas.add(btnCadastrarReserva);

        btnConsultarReserva.setText("Consultar");
        btnConsultarReserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultarReservaMouseClicked(evt);
            }
        });
        menuReservas.add(btnConsultarReserva);

        btnFinalizarReserva.setText("Finalizar");
        btnFinalizarReserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFinalizarReservaMouseClicked(evt);
            }
        });
        menuReservas.add(btnFinalizarReserva);

        jMenuBar1.add(menuReservas);

        menuRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/document_paperclip_list_paper_icon_219544.png"))); // NOI18N
        menuRelatorio.setText("Relatório   ");

        jMenu17.setText("Financeiro");

        jMenuItem28.setText("Contas a serem pagas");
        jMenu17.add(jMenuItem28);

        jMenuItem29.setText("Contas a serem recebidas");
        jMenu17.add(jMenuItem29);

        jMenuItem30.setText("Balanço");
        jMenu17.add(jMenuItem30);

        menuRelatorio.add(jMenu17);

        jMenu18.setText("Reservas");

        jMenuItem31.setText("Quartos Disponíveis");
        jMenu18.add(jMenuItem31);

        jMenuItem32.setText("Quartos Ocupados");
        jMenu18.add(jMenuItem32);

        jMenuItem33.setText("Reservas Futuras");
        jMenu18.add(jMenuItem33);

        menuRelatorio.add(jMenu18);

        jMenu19.setText("Vendas");

        jMenuItem34.setText("Vendas Mensais");
        jMenu19.add(jMenuItem34);

        jMenuItem35.setText("Vendas Anuais");
        jMenu19.add(jMenuItem35);

        menuRelatorio.add(jMenu19);

        btnRelatorioHospedes.setText("Hospedes");
        btnRelatorioHospedes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRelatorioHospedesMouseClicked(evt);
            }
        });
        menuRelatorio.add(btnRelatorioHospedes);

        btnRelatorioFuncionarios.setText("Funcionários");
        btnRelatorioFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRelatorioFuncionariosMouseClicked(evt);
            }
        });
        menuRelatorio.add(btnRelatorioFuncionarios);

        btnRelatorioFornecedores.setText("Fornecedores");
        btnRelatorioFornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRelatorioFornecedoresMouseClicked(evt);
            }
        });
        menuRelatorio.add(btnRelatorioFornecedores);

        jMenuBar1.add(menuRelatorio);

        menuSeguranca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1458264596_authorisation_lock_padlock_safe_password_privacy_security_icon-icons.com_55333.png"))); // NOI18N
        menuSeguranca.setText("Segurança   ");

        tbnFazerBackup.setText("Fazer Backup");
        tbnFazerBackup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbnFazerBackupMouseClicked(evt);
            }
        });
        menuSeguranca.add(tbnFazerBackup);

        btnRestaurarBackup.setText("Restaurar Backup");
        btnRestaurarBackup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRestaurarBackupMouseClicked(evt);
            }
        });
        menuSeguranca.add(btnRestaurarBackup);

        jMenuBar1.add(menuSeguranca);

        menuServicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/support_call_center_help_information_customer_service_icon_140644.png"))); // NOI18N
        menuServicos.setText("Serviços");

        btnCadastrarServicos.setText("Cadastrar Serviços");
        btnCadastrarServicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastrarServicosMouseClicked(evt);
            }
        });
        menuServicos.add(btnCadastrarServicos);

        btnConsultarServicos.setText("Consultar Serviços");
        btnConsultarServicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultarServicosMouseClicked(evt);
            }
        });
        btnConsultarServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarServicosActionPerformed(evt);
            }
        });
        menuServicos.add(btnConsultarServicos);

        jMenuBar1.add(menuServicos);

        menuFinanceiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3700465-business-calculating-calculator-finance-maths-technological_108748.png"))); // NOI18N
        menuFinanceiro.setText("Financeiro");

        jMenu15.setText("Contas a serem pagas");

        jMenuItem9.setText("Cadastrar");
        jMenu15.add(jMenuItem9);

        jMenuItem10.setText("Consultar");
        jMenu15.add(jMenuItem10);

        menuFinanceiro.add(jMenu15);

        jMenu16.setText("Contas a seres recebidas");

        jMenuItem11.setText("Cadastrar");
        jMenu16.add(jMenuItem11);

        jMenuItem12.setText("Receber");
        jMenu16.add(jMenuItem12);

        menuFinanceiro.add(jMenu16);

        btnBalanco.setText("Balanço");
        btnBalanco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBalancoMouseClicked(evt);
            }
        });
        btnBalanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBalancoActionPerformed(evt);
            }
        });
        menuFinanceiro.add(btnBalanco);

        jMenuBar1.add(menuFinanceiro);

        menuVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shoppaymentorderbuy-29_icon-icons.com_73875.png"))); // NOI18N
        menuVendas.setText("Vendas");

        btnProdutos.setText("Produtos");
        btnProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProdutosMouseClicked(evt);
            }
        });
        menuVendas.add(btnProdutos);

        btnServicos.setText("Serviços");
        btnServicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnServicosMouseClicked(evt);
            }
        });
        btnServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServicosActionPerformed(evt);
            }
        });
        menuVendas.add(btnServicos);

        jMenuBar1.add(menuVendas);

        menuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_account_off_door_arrow_leave_ui_exit_logout_icon_210826.png"))); // NOI18N
        menuSair.setText("Sair");
        jMenuBar1.add(menuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(telaFundo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(telaFundo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void menuCadastroHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroHospedeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadastroHospedeActionPerformed

    private void btnServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnServicosActionPerformed

    private void btnBalancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBalancoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBalancoActionPerformed

    private void btnCadastrarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarFuncionariosActionPerformed
    TelaCadastroFuncionario telaFuncionario = new TelaCadastroFuncionario();
    telaFundo.add(telaFuncionario);
    telaFuncionario.setVisible(true);
    // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastrarFuncionariosActionPerformed

    private void btnCadastrarReservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarReservaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastrarReservaMouseClicked

    private void btnConsultarReservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarReservaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarReservaMouseClicked

    private void btnFinalizarReservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinalizarReservaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFinalizarReservaMouseClicked

    private void btnConsultarServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarServicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarServicosActionPerformed

    private void btnProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdutosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProdutosMouseClicked

    private void btnServicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnServicosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnServicosMouseClicked

    private void btnBalancoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBalancoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBalancoMouseClicked

    private void btnCadastrarServicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarServicosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastrarServicosMouseClicked

    private void btnConsultarServicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarServicosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarServicosMouseClicked

    private void tbnFazerBackupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbnFazerBackupMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbnFazerBackupMouseClicked

    private void btnRestaurarBackupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRestaurarBackupMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRestaurarBackupMouseClicked

    private void btnRelatorioHospedesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRelatorioHospedesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRelatorioHospedesMouseClicked

    private void btnRelatorioFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRelatorioFuncionariosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRelatorioFuncionariosMouseClicked

    private void btnRelatorioFornecedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRelatorioFornecedoresMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRelatorioFornecedoresMouseClicked

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAcesso;
    private javax.swing.JMenuItem btnBalanco;
    private javax.swing.JMenuItem btnCadastrarFuncionarios;
    private javax.swing.JMenuItem btnCadastrarReserva;
    private javax.swing.JMenuItem btnCadastrarServicos;
    private javax.swing.JLabel btnCargo;
    private javax.swing.JMenuItem btnConsultarReserva;
    private javax.swing.JMenuItem btnConsultarServicos;
    private javax.swing.JMenuItem btnFinalizarReserva;
    private javax.swing.JLabel btnNome;
    private javax.swing.JMenuItem btnProdutos;
    private javax.swing.JMenuItem btnRelatorioFornecedores;
    private javax.swing.JMenuItem btnRelatorioFuncionarios;
    private javax.swing.JMenuItem btnRelatorioHospedes;
    private javax.swing.JMenuItem btnRestaurarBackup;
    private javax.swing.JButton btnSair;
    private javax.swing.JMenuItem btnServicos;
    private com.toedter.calendar.JCalendar jCalendar1;
    private com.toedter.calendar.JCalendar jCalendar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JMenuItem menuCadastroHospede;
    private javax.swing.JMenu menuCadastros;
    private javax.swing.JMenuItem menuConsultaHospede;
    private javax.swing.JMenu menuFinanceiro;
    private javax.swing.JMenu menuRelatorio;
    private javax.swing.JMenu menuReservas;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenu menuSeguranca;
    private javax.swing.JMenu menuServicos;
    private javax.swing.JMenu menuVendas;
    private javax.swing.JMenuItem tbnFazerBackup;
    private javax.swing.JDesktopPane telaFundo;
    // End of variables declaration//GEN-END:variables
}
