/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens;

/**
 *
 * @author 0069837
 */
public class TelaListagemHospedes extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaListagemFornecedores
     */
    public TelaListagemHospedes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPListagemHospedes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTHospedes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTBuscarNomeHospede = new javax.swing.JTextField();
        btnBuscaFuncionarios = new javax.swing.JButton();
        btnEliminarFuncionarios = new javax.swing.JButton();
        btnSairFuncionarios = new javax.swing.JButton();

        jPListagemHospedes.setBorder(javax.swing.BorderFactory.createTitledBorder("LISTAGEM - HOSPEDES"));

        jTHospedes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Título 1", "Título 2", "Título 3", "Título 4"
            }
        ));
        jScrollPane1.setViewportView(jTHospedes);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel1.setText("Buscar");

        btnBuscaFuncionarios.setText("Buscar");

        btnEliminarFuncionarios.setText("Eliminar");

        btnSairFuncionarios.setText("Sair");

        javax.swing.GroupLayout jPListagemHospedesLayout = new javax.swing.GroupLayout(jPListagemHospedes);
        jPListagemHospedes.setLayout(jPListagemHospedesLayout);
        jPListagemHospedesLayout.setHorizontalGroup(
            jPListagemHospedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPListagemHospedesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTBuscarNomeHospede, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(btnBuscaFuncionarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarFuncionarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSairFuncionarios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPListagemHospedesLayout.setVerticalGroup(
            jPListagemHospedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPListagemHospedesLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPListagemHospedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTBuscarNomeHospede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscaFuncionarios)
                    .addComponent(btnEliminarFuncionarios)
                    .addComponent(btnSairFuncionarios))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPListagemHospedes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPListagemHospedes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscaFuncionarios;
    private javax.swing.JButton btnEliminarFuncionarios;
    private javax.swing.JButton btnSairFuncionarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPListagemHospedes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTBuscarNomeHospede;
    private javax.swing.JTable jTHospedes;
    // End of variables declaration//GEN-END:variables
}
