/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens;

/**
 *
 * @author 0069837
 */
public class TelaListagemFornecedores extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaListagemFornecedores
     */
    public TelaListagemFornecedores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPListagemFornecedores = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTFornecedores = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTBuscarNomeFornecedores = new javax.swing.JTextField();
        btnBuscarFornecedor = new javax.swing.JButton();
        btnEliminarFornecedor = new javax.swing.JButton();
        btnSairFornecedor = new javax.swing.JButton();

        jPListagemFornecedores.setBorder(javax.swing.BorderFactory.createTitledBorder("LISTAGEM - FORNECEDORES"));

        jTFornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Título 1", "Título 2", "Título 3", "Título 4"
            }
        ));
        jScrollPane1.setViewportView(jTFornecedores);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel1.setText("Buscar");

        btnBuscarFornecedor.setText("Buscar");

        btnEliminarFornecedor.setText("Eliminar");

        btnSairFornecedor.setText("Sair");

        javax.swing.GroupLayout jPListagemFornecedoresLayout = new javax.swing.GroupLayout(jPListagemFornecedores);
        jPListagemFornecedores.setLayout(jPListagemFornecedoresLayout);
        jPListagemFornecedoresLayout.setHorizontalGroup(
            jPListagemFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPListagemFornecedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTBuscarNomeFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(btnBuscarFornecedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarFornecedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSairFornecedor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPListagemFornecedoresLayout.setVerticalGroup(
            jPListagemFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPListagemFornecedoresLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPListagemFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTBuscarNomeFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarFornecedor)
                    .addComponent(btnEliminarFornecedor)
                    .addComponent(btnSairFornecedor))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPListagemFornecedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPListagemFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarFornecedor;
    private javax.swing.JButton btnEliminarFornecedor;
    private javax.swing.JButton btnSairFornecedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPListagemFornecedores;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTBuscarNomeFornecedores;
    private javax.swing.JTable jTFornecedores;
    // End of variables declaration//GEN-END:variables
}
